name: Publish qwc-base-db docker image

on: [push, workflow_dispatch]

jobs:

    build:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            echo ::set-output name=tag::${GITHUB_REF:10}
          else
            echo ::set-output name=tag::
          fi

      - name: Build and publish docker image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: neotrade-ts/qwc-base-db
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: "latest,${{ steps.get_tag.outputs.tag }}"
          workdir: .
          platforms: linux/arm64,linux/amd64
